version: 2
jobs:
  build:
    working_directory: ~/paintroid
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_EMULATOR_TARGET: "24"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Paintroid/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y --no-install-recommends libpulse0
      - run:
          name: Setup emulator
          command: echo y | sdkmanager "platform-tools" "platforms;android-${ANDROID_EMULATOR_TARGET}" "emulator" "system-images;android-${ANDROID_EMULATOR_TARGET};default;armeabi-v7a" && echo "no" | avdmanager create avd --force -n test -k "system-images;android-${ANDROID_EMULATOR_TARGET};default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && $ANDROID_HOME/emulator/emulator -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Paintroid/build.gradle" }}
      - run:
          name: Run Paintroid Module Unit Tests
          command: ./gradlew :Paintroid:testDebugUnitTest
      - run:
          name: Run Lint Tests
          command: ./gradlew lint
      - run:
          name: Run CheckStyle Tests
          command: ./gradlew checkstyle
      - run:
          name: Run PMD Tests
          command: ./gradlew pmd
      - store_artifacts:
          path: Paintroid/build/reports
      - store_artifacts:
          path: app/build/reports
      - store_artifacts:
          path: colorpicker/build/reports
      - store_test_results:
          path: Paintroid/build/test-results
      - run:
          name: Wait for emulator bootup
          command: |
            circle-android wait-for-boot
            adb shell input keyevent 82
      - run:
          name: Run Tests
          command: ./gradlew :Paintroid:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.package="org.catrobat.paintroid.test.junit"
      - store_test_results:
          path: Paintroid/build/test-results
      - store_artifacts:
          path: Paintroid/build/reports
